# Generated by Django 3.2.14 on 2022-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.JSONField(blank=True, default=dict, null=True)),
                ('eng', models.CharField(max_length=250)),
                ('slo', models.CharField(max_length=250)),
                ('alts', models.JSONField(blank=True, default=dict, null=True)),
                ('info', models.JSONField(blank=True, default=dict, null=True)),
                ('eng_audio', models.CharField(blank=True, max_length=25, null=True)),
                ('slo_audio', models.CharField(blank=True, max_length=25, null=True)),
                ('audio', models.CharField(default='false', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dialogue', 'dialogue'), ('news', 'news'), ('verb', 'verb'), ('keywords', 'keywords')], default='news', max_length=25)),
                ('actors', models.CharField(choices=[('none', 'none'), ('rok&nina', 'rok & nina'), ('gašper&špela', 'gašper & špela')], default='', max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='images/lesson')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('slo_title', models.CharField(blank=True, max_length=200)),
                ('slo_description', models.CharField(blank=True, max_length=1000)),
                ('slo_date', models.CharField(blank=True, max_length=200)),
                ('entries', models.JSONField(blank=True, default=list, null=True)),
                ('missing_words', models.JSONField(blank=True, default=dict, null=True)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('order', models.JSONField(blank=True, default=list, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slo_title', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
