# Generated by Django 3.2.14 on 2022-12-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_lesson_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_live',
        ),
    ]
