# Generated by Django 3.2.14 on 2022-12-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_remove_lesson_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_live',
            field=models.CharField(default='false', max_length=25),
        ),
    ]
